defaults:
  - _self_
  - model: XR-TFMR
  - data: Wiki10-31k

tasks: ["predict"]


eval:
  metrics: ["mrr","ndcg","precision","recall"]
  thresholds: [1,5,10]
  label_cls: ["all", "full", "few", "tail"]

log:
  dir: resource/log/

model_checkpoint:
  dir: resource/model_checkpoint/

prediction:
  dir: resource/prediction/

ranking:
  dir: resource/ranking/

result:
  dir: resource/result/








